### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by JakovlevDS** [transloadit/node-sdk#60]
Hello there!

I'm trying to use Transloadit in my React project and I have the next error message when I require transloadit:
![image](https://user-images.githubusercontent.com/781737/47767211-33e4ae80-dd05-11e8-8e62-f5d39648412e.png)

What I did:
- installed transloadit by `npm install --save transloadit`
- added `TransloaditClient = require('transloadit')` to one of my components
- tried to compile and I've got the error.

my setup:
- node v8.12.0 (npm v6.4.1)
- webpack@1.13.2 (tried the latest version with no luck)

What am I doing wrong?

**Comment by kvz** [comment]
Hi! I'm afraid we don't really support client side integration with our Node.js SDK. Maybe it's possible to get it to work, but likely it's not so efficient even if you succeed with a lot of Webpack magic. Have you considered to use https://uppy.io instead? This is also a project by Transloadit and it works well with Browsers and React Native. And you don't have to use any UI components if that's why maybe you decided to try the Node SDK. Does that help?

**Comment by JakovlevDS** [comment]
Yes, it makes sense. Thank you for clarification.
